;;; ... my-modes.el --- customize the language mode emacs dissplays ...

;;; ... matlab mode ...
(require 'matlab-load)
(custom-set-variables
 '(matlab-shell-command-switches '("-nodesktop -nosplash")))
;;; ................... 

(provide 'my-modes)
